package br.udesc.ceavi.pin.infosaude.view.component.campoDeAcao;

import br.udesc.ceavi.pin.infosaude.control.CampanhaControl;
import br.udesc.ceavi.pin.infosaude.control.VacinaControl;
import br.udesc.ceavi.pin.infosaude.modelo.Campanha;
import br.udesc.ceavi.pin.infosaude.modelo.Vacina;
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class InternalFrameLancamentoDeRelatorio extends javax.swing.JInternalFrame {

    private JComboBox cbEscolha;
    private List date;

    /**
     * Creates new form InternalFrameLancamentoDeRelatori
     */
    public InternalFrameLancamentoDeRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpSelecaoRelatorio = new javax.swing.JPanel();
        cbRelatio = new javax.swing.JComboBox<>();
        btnExecutarRelatorio = new javax.swing.JButton();
        jpTipo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Tela de Relatórios");

        jpSelecaoRelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpSelecaoRelatorio.setMaximumSize(new java.awt.Dimension(600, 100));
        jpSelecaoRelatorio.setMinimumSize(new java.awt.Dimension(600, 100));
        jpSelecaoRelatorio.setPreferredSize(new java.awt.Dimension(600, 100));
        jpSelecaoRelatorio.setLayout(new java.awt.GridBagLayout());

        cbRelatio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Relatorio a Ser Gerado", "Efetividade de Campanha", "Pendencia Com Vacina" }));
        cbRelatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRelatioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jpSelecaoRelatorio.add(cbRelatio, gridBagConstraints);

        btnExecutarRelatorio.setText("Executar Relatorio");
        btnExecutarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarRelatorioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 0, 0);
        jpSelecaoRelatorio.add(btnExecutarRelatorio, gridBagConstraints);

        jpTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        javax.swing.GroupLayout jpTipoLayout = new javax.swing.GroupLayout(jpTipo);
        jpTipo.setLayout(jpTipoLayout);
        jpTipoLayout.setHorizontalGroup(
            jpTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpTipoLayout.setVerticalGroup(
            jpTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Publico Alvo", "Efitividade %", "Num Presença", "Num Faltosos", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpSelecaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpSelecaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jpTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRelatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRelatioActionPerformed
        GridBagConstraints cons = new GridBagConstraints();
        if (this.jpSelecaoRelatorio.getComponentCount() == 3) {
            this.jpSelecaoRelatorio.remove(2);
        }
        cons.gridx = 0;
        cons.gridy = 1;
        cons.fill = GridBagConstraints.HORIZONTAL;
        if (cbRelatio.getSelectedIndex() == 1) {
            try {
                CampanhaControl controleCampanha = new CampanhaControl();
                List<Campanha> lista = controleCampanha.getCampanhas();
                date = lista;
                cbEscolha = new JComboBox(lista.toArray());
                jpSelecaoRelatorio.add(cbEscolha, cons);
                jpTipo.setBorder(BorderFactory.createTitledBorder("Campanha"));
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro na Coneção no Banco de Dados");
            }
        } else if (cbRelatio.getSelectedIndex() == 2) {
            try {
                VacinaControl controleVacina = new VacinaControl();
                List<Vacina> lista = controleVacina.getVacinas();
                for (int i = 0; i < lista.size(); i++) {
                    lista.get(i).setPublicosAlvos(controleVacina.obterPublicoAlvo(lista.get(i).getId()));
                }
                date = lista;
                cbEscolha = new JComboBox(lista.toArray());
                jpSelecaoRelatorio.add(cbEscolha, cons);
                jpTipo.setBorder(BorderFactory.createTitledBorder("Campanha"));
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro na Coneção no Banco de Dados");
            }
        }
        cbEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolhaRelacotioActionPerformed(evt);
            }
        });
        jpSelecaoRelatorio.revalidate();
        jpSelecaoRelatorio.repaint();
    }//GEN-LAST:event_cbRelatioActionPerformed

    private void btnEscolhaRelacotioActionPerformed(ActionEvent evt) {
        if (cbEscolha.getSelectedIndex() == 0) {
            System.out.println("Escolha 1");
        } else if (cbEscolha.getSelectedIndex() == 1) {
            System.out.println("Escolha 2");
        }
    }

    private void btnExecutarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarRelatorioActionPerformed

    }//GEN-LAST:event_btnExecutarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecutarRelatorio;
    private javax.swing.JComboBox<String> cbRelatio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpSelecaoRelatorio;
    private javax.swing.JPanel jpTipo;
    // End of variables declaration//GEN-END:variables
}
